title: Lunean
description: Lunean
author:
  name: Augustin Luna

theme: minima

# # Minima social links
# twitter_username: canninl
# github_username: cannin
# linkedin_username: augustin-luna
# rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

skin: red

minima:
  date_format: "%Y-%m-%d"

  social_links:
    twitter: canninl
    github: cannin

  skin: red

google_analytics: UA-317478-16

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

header_pages:
  - about.md
  - archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
