title: Lunean
description: Lunean
author:
  name: Augustin Luna
  email: info@lunean.com

theme: minima

# # Minima social links
# twitter_username: canninl
# github_username: cannin
# linkedin_username: augustin-luna
# rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

  social_links:
    twitter: jekyllrb
    github: jekyll
    stackoverflow: "11111"

google_analytics: UA-NNNNNNNN-N

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
